### ISSUE TITLE
Outgoing chat messages are not blocked

### ISSUE THREAD

**Issue by Ssesmar** [Legacy-of-Sylvanaar/prat-3-0#134]
If I check the box "Block message" (prevents this message from being displayed) under Interface -> Addons -> Prat -> Extra Stuff -> Filtering -> Outgoing messages. the whole message is still displayed, only the set word is either replaced or hidden, but not the complete sentence

**Comment by plusmouse** [comment]
By "displayed" do you mean displayed in your game client or as in displayed on the recipient's device?

**Comment by Ssesmar** [comment]
both. if i enter a replacement text, it will be displayed to me and to the recipient. if I replace the text with "no input" the word is also hidden for both. like I never wrote it. I would just like to completely block a message that contains such a "filtered word" so that the message cannot be sent at all.
or was the tick box meant "block message" (prevents the message from being displayed)?
like in the picture
[https://i.postimg.cc/nc30pR1W/prat.png](url)

**Comment by plusmouse** [comment]
I suspect that the option is copied over from the Inbound pattern options, and hasn't been tested against outgoing messages.

![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/60280559/2eb60194-6a86-4028-86b9-5544c1f53181)

It would be weird to have an option that specially blocks message be labelled with "prevent from being displayed" rather than worded as "prevent from being sent"

**Comment by plusmouse** [comment]
I've fixed the issue in the latest alpha. Available from Curseforge or Wago shortly.
