### ISSUE TITLE
Chattwindows1text not showing the text

### ISSUE THREAD

**Issue by Ssesmar** [Legacy-of-Sylvanaar/prat-3-0#165]
**Describe the bug**
The texts are there, but are displayed without font color, so only if you copy/paste them can you see the text is there.

**To Reproduce**
used the button to open the chat copy/paste window

**Screenshots**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/J2vZ7yC/praterrorjpg.jpg" alt="praterrorjpg" border="0"></a>

**Version Information (please complete the following information):**
 - Wow Version: Retail
 - Prat Version: Prat-3.0-3.9.43

**Comment by plusmouse** [comment]
Do you have any addons that may modify the appearance of the Prat text export frame? I can't replicate this issue on my device, it displays correctly.

**Comment by Ssesmar** [comment]
sorry for the long time. No, I have that even though I only have Prat active. Prat 3 and Prat 3 Libarys. I also have another strange error. When I use the button to copy the chat, my fps drops extremely low.
before
<a href="https://ibb.co/XJX8938"><img src="https://i.ibb.co/DK4pN8p/fps-before.jpg" alt="fps-before" border="0"></a>

and if i open the copy windows
<a href="https://ibb.co/7yZc6Ld"><img src="https://i.ibb.co/mz2sMgV/fps-after.jpg" alt="fps-after" border="0"></a>

**Comment by plusmouse** [comment]
I've added a fix for this issue into the latest alpha. Available shortly. Please comment here if the issue isn't resolved.
[Prat-3.0-3.9.43-3-gb7152f1.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/13754642/Prat-3.0-3.9.43-3-gb7152f1.zip)

**Comment by Mitalie** [comment]
While the change to `StripHyperlinks` takes care of color sequences that might have been escaping the previous patterns, it's not enough alone. At least `|K` protected strings must be stripped out separately - if any are present, the editbox will be empty (actually empty, not just display issue). Also, removing link brackets reduces readability of the copied text - `StripHyperlinks(msg, false, true)` would preserve brackets while removing colors.

As far as I know, the FPS drop is just an unavoidable consequence of putting a huge amount of text in an editbox at once so that it can be copied with ctrl-C.

**Comment by plusmouse** [comment]
Thanks. I've fixed both those issues now. Find the fix in the latest alpha.
