### ISSUE TITLE
chat tab not staying invisible

### ISSUE THREAD

**Issue by Daeveren** [Legacy-of-Sylvanaar/prat-3-0#74]
**Describe the bug**
Sometimes the chat tab remains active and does not fade.

**To Reproduce**
Cannot find specific steps to reproduce it. But it happens frequently.

**Version Information (please complete the following information):**
Using 3.9.12, but the same thing happens since before patch 10.0

Note that both active and not active chat tab alpha are set to 0 in the ChatTabs module. Perhaps at some point, something prevents Prat from setting the chat tab to 0 alpha. When it happens, if I mouseover on it, it then correctly starts to fade away into 0 alpha.

![0VGgNQYwt9](https://user-images.githubusercontent.com/6321337/202803058-01b3e296-266d-4a5f-8c46-d274ba8c1371.png)

![N1EqaXgkKY](https://user-images.githubusercontent.com/6321337/202803071-7355e45b-107c-4171-8f02-0f032830fb8d.png)

![image](https://user-images.githubusercontent.com/6321337/202803168-711c29ac-eea5-4951-8586-a3f8f7e124e8.png)

**Comment by plusmouse** [comment]
I think I'm getting confused. Is the chat tab button _ever_ supposed to show when Active Alpha is set to 0, including when mousing over the chat frame?

**Comment by Rezy942** [comment]
> I think I'm getting confused. Is the chat tab button _ever_ supposed to show when Active Alpha is set to 0, including when mousing over the chat frame?

No, ideally the buttons should completely fade out when mouse is NOT in chat window. When mouse is in chat window, tabs show up again.
Author's issue is same for me and my wife and few of my guild mates that use Prat - something breaks Prat tab fade either after UI reload or some other unknown things, exactly as author describes.

Its similar to the scroll wheel issue that you fixed recently - after reload it was appearing, you had to hover over it and THEN it disappears properly, and same thing is happening with these tabs. But the cause is uknown.

As I mentioned in other post - BasicChatMods addon tab fade works flawlessly if that helps code-wise.

**Comment by Daeveren** [comment]
> I think I'm getting confused. Is the chat tab button _ever_ supposed to show when Active Alpha is set to 0, including when mousing over the chat frame?

Just as @Rezy942 mentioned - there's no reason that the chat tab button remains visible 'sometimes' and sometimes correctly dissapears. I'm talking about not interacting with the chat window at all, the chat tab button remains visible for the remainder of the gaming session, where it should actually be hidden.

My understanding is that the 2 settings do this:
- active alpha - should make sure that the chat tab button stays hidden when "the chat channel is active" (I guess what would count as 'active' is: you write in the chat, you are scrolling, you are mouseovering that specific chat window)
-  "not active alpha" would be for "when the chat channel is no longer active" (my understanding would be that no action has been done to the chat window for X seconds already and the mouse cursor is not hovering the chat window).

So, from my understanding (and it must be how it originally worked over the years, not sure when exactly it broke) - with both settings to 0%, the chat tab button should not be visible at all on the screen, unless you specifically mouseover directly to the chat tab button - then it needs to show up because that's how you can interact with the chat settings/channels etc.

**Comment by Rezy942** [comment]
Lastly just wanted to mention that yes there have been a bunch of reports of this already, but it may seem like not a "widespread" sort of issue. But believe me - there are so many Prat users out there that do not know or bother to use github to report these things. They just go "meh". 
I hope you can find the solution in the end, because other than that, the addon is flawless :)
Any way I can help let me know, thanks

**Comment by plusmouse** [comment]
I've put a fix in the latest alpha (which will be available from Curseforge and Wago shortly)

**Comment by plusmouse** [comment]
Scratch that, still broken, but I've got  a way to replicate the bug now.

**Comment by plusmouse** [comment]
And got another fix. Please try the new latest alpha.
[Prat-3.0-3.9.27-6-gc3b332a.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/11581527/Prat-3.0-3.9.27-6-gc3b332a.zip)

**Comment by Rezy942** [comment]
Great news! Will try it out right away. Thank you for your work <3

**Comment by Daeveren** [comment]
> And got another fix. Please try the new latest alpha. [Prat-3.0-3.9.27-6-gc3b332a.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/11581527/Prat-3.0-3.9.27-6-gc3b332a.zip)

Thanks for your effort! I'm away from home for a few days so I can't test it, but out of curiosity, what was triggering it, I mean any ingame user action?

**Comment by plusmouse** [comment]
Triggering the chat by mousing over it while another window was on top of it, so maybe a loading screen, or in my case, the map.

**Comment by Rezy942** [comment]
Using: Prat-3.0-3.9.29

Hi, is the fix for this tab fading issue in the alpha or already in latest release?
Because in latest release i am having this issue. In this case it was after entering UI to change drake appearance.
My chat is bottom left of screen, and all is set to 0 transparency.
![image](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/122007087/69ab30f4-7343-4ea2-9e6a-d4686581bc59)

So far i encountered this issue about twice in a couple days.
Thanks

**Comment by plusmouse** [comment]
https://www.curseforge.com/wow/addons/prat-3-0/files/4561865

**Comment by Rezy942** [comment]
Thank you for such quick fixes!!!! :)

**Comment by Rezy942** [comment]
Update: also wanted to mention other ways to reproduce the bug as I just rememebered:
1. Opening trade post
2. Barber shop

I would assume any other feature that "fades" the UI will cause this issue, perhaps dependant on chat location and fading settings of course, which is why it might be difficult to reproduce.
